// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fachain/feeabstraction/callbacks.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SwapCallback struct {
	TokenIn types.Coin `protobuf:"bytes,1,opt,name=token_in,json=tokenIn,proto3" json:"token_in" yaml:"token_in"`
}

func (m *SwapCallback) Reset()         { *m = SwapCallback{} }
func (m *SwapCallback) String() string { return proto.CompactTextString(m) }
func (*SwapCallback) ProtoMessage()    {}
func (*SwapCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_758d6f5cd53bfe3d, []int{0}
}
func (m *SwapCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SwapCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SwapCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SwapCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapCallback.Merge(m, src)
}
func (m *SwapCallback) XXX_Size() int {
	return m.Size()
}
func (m *SwapCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapCallback.DiscardUnknown(m)
}

var xxx_messageInfo_SwapCallback proto.InternalMessageInfo

func (m *SwapCallback) GetTokenIn() types.Coin {
	if m != nil {
		return m.TokenIn
	}
	return types.Coin{}
}

type FeeReceiveCallback struct {
}

func (m *FeeReceiveCallback) Reset()         { *m = FeeReceiveCallback{} }
func (m *FeeReceiveCallback) String() string { return proto.CompactTextString(m) }
func (*FeeReceiveCallback) ProtoMessage()    {}
func (*FeeReceiveCallback) Descriptor() ([]byte, []int) {
	return fileDescriptor_758d6f5cd53bfe3d, []int{1}
}
func (m *FeeReceiveCallback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeeReceiveCallback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeeReceiveCallback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeeReceiveCallback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeReceiveCallback.Merge(m, src)
}
func (m *FeeReceiveCallback) XXX_Size() int {
	return m.Size()
}
func (m *FeeReceiveCallback) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeReceiveCallback.DiscardUnknown(m)
}

var xxx_messageInfo_FeeReceiveCallback proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SwapCallback)(nil), "fachain.feeabstraction.SwapCallback")
	proto.RegisterType((*FeeReceiveCallback)(nil), "fachain.feeabstraction.FeeReceiveCallback")
}

func init() {
	proto.RegisterFile("fachain/feeabstraction/callbacks.proto", fileDescriptor_758d6f5cd53bfe3d)
}

var fileDescriptor_758d6f5cd53bfe3d = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xbd, 0x4a, 0x03, 0x41,
	0x14, 0x85, 0x77, 0x1b, 0x95, 0x55, 0x10, 0x42, 0xf0, 0x27, 0xc5, 0x44, 0xb6, 0x10, 0x9b, 0xcc,
	0x10, 0x6d, 0xc4, 0x32, 0x01, 0xc1, 0xc2, 0x66, 0xed, 0x04, 0x91, 0x3b, 0xc3, 0xdd, 0xcd, 0x90,
	0xd9, 0xb9, 0x4b, 0x66, 0x8c, 0xe6, 0x2d, 0x7c, 0xac, 0x94, 0x29, 0xad, 0x82, 0xec, 0xbe, 0x81,
	0x4f, 0x20, 0xfb, 0x93, 0x42, 0xbb, 0x03, 0xf7, 0xbb, 0xe7, 0x70, 0x4e, 0x74, 0x99, 0x82, 0x9a,
	0x81, 0xb6, 0x22, 0x45, 0x04, 0xe9, 0xfc, 0x02, 0x94, 0xd7, 0x64, 0x85, 0x02, 0x63, 0x24, 0xa8,
	0xb9, 0xe3, 0xc5, 0x82, 0x3c, 0xf5, 0x4e, 0x3a, 0x8e, 0xff, 0xe5, 0x06, 0xfd, 0x8c, 0x32, 0x6a,
	0x10, 0x51, 0xab, 0x96, 0x1e, 0x30, 0x45, 0x2e, 0x27, 0x27, 0x24, 0x38, 0x14, 0xcb, 0xb1, 0x44,
	0x0f, 0x63, 0xa1, 0x48, 0xdb, 0xf6, 0x1e, 0xbf, 0x44, 0x47, 0x4f, 0xef, 0x50, 0x4c, 0xbb, 0x90,
	0xde, 0x63, 0x74, 0xe0, 0x69, 0x8e, 0xf6, 0x55, 0xdb, 0xb3, 0xf0, 0x22, 0xbc, 0x3a, 0xbc, 0x3e,
	0xe7, 0xad, 0x05, 0xaf, 0x2d, 0x78, 0x67, 0xc1, 0xa7, 0xa4, 0xed, 0xe4, 0x74, 0xbd, 0x1d, 0x06,
	0x3f, 0xdb, 0xe1, 0xf1, 0x0a, 0x72, 0x73, 0x17, 0xef, 0x1e, 0xe3, 0x64, 0xbf, 0x91, 0x0f, 0x36,
	0xee, 0x47, 0xbd, 0x7b, 0xc4, 0x04, 0x15, 0xea, 0x25, 0xee, 0x42, 0x26, 0xc9, 0xba, 0x64, 0xe1,
	0xa6, 0x64, 0xe1, 0x77, 0xc9, 0xc2, 0xcf, 0x8a, 0x05, 0x9b, 0x8a, 0x05, 0x5f, 0x15, 0x0b, 0x9e,
	0x6f, 0x33, 0xed, 0x67, 0x6f, 0x92, 0x2b, 0xca, 0x85, 0xa5, 0xba, 0x17, 0x98, 0x91, 0x01, 0xe9,
	0x44, 0x0a, 0xa3, 0x76, 0x9e, 0x8f, 0xff, 0x03, 0xf9, 0x55, 0x81, 0x4e, 0xee, 0x35, 0x7d, 0x6e,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x08, 0xd8, 0x26, 0x47, 0x01, 0x00, 0x00,
}

func (m *SwapCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SwapCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SwapCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TokenIn.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintCallbacks(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FeeReceiveCallback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeeReceiveCallback) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeeReceiveCallback) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintCallbacks(dAtA []byte, offset int, v uint64) int {
	offset -= sovCallbacks(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SwapCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TokenIn.Size()
	n += 1 + l + sovCallbacks(uint64(l))
	return n
}

func (m *FeeReceiveCallback) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovCallbacks(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCallbacks(x uint64) (n int) {
	return sovCallbacks(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SwapCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SwapCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SwapCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenIn", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCallbacks
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCallbacks
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TokenIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCallbacks(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCallbacks
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeeReceiveCallback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeeReceiveCallback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeeReceiveCallback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipCallbacks(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCallbacks
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCallbacks(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCallbacks
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCallbacks
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCallbacks
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCallbacks
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCallbacks
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCallbacks        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCallbacks          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCallbacks = fmt.Errorf("proto: unexpected end of group")
)
